Changing the orientation of credit card input
da1help/react-native-credit-card-input pull request #3
Opened 2020-06-22 12:31 UTC by pejann

This PR changes the orientation of the credit card input to vertical.
That way all the fields are displayed in screen and can be filled by auto-fill apps.

2020-06-22 14:33 UTC, ghost requested changes

2020-06-22 14:33 UTC, henriqu7 commented on src/CreditCardInput.js
> +              containerStyle={[inputContainerStyle, { marginBottom: 10 }]} /> }
Nāo seria ideal colocar a margem dentro do estilo inputContainerStyle? acredito que ficaria mais organizado

2020-06-22 14:33 UTC, henriqu7 commented on src/CreditCardInput.js
> +          <View style={{ flexDirection: "row", marginTop: 10, marginBottom: 10 }}>
Acredito que aqui seria bom criar um estilo próprio para essa View para nāo ficar com o estilo inline

2020-06-22 14:33 UTC, henriqu7 commented on src/CreditCardInput.js
> +            <View style={{ flex: 1, paddingRight: 10 }}>
Aqui também, mesmo que seja apenas duas propriedades

2020-06-22 14:33 UTC, henriqu7 commented on src/CreditCardInput.js
> +            <View style={{ flex: 1 }}>
Apenas uma propriedade, mas creio que tambem seja uma boa criar um estilo para sabermos o que essa View é

2020-06-22 18:50 UTC, carlosmorette approved these changes
Ok

2020-06-23 21:24 UTC, ghost approved these changes

2020-06-23 21:25 UTC, henriqu7 commented
tudo ok

2020-06-23 21:25 UTC, merged